session_name: web
start_directory: "~/Documents/topics/personal/duclos-cavalcanti.github.io/"
windows:
  - window_name: readme
    panes:
      - nvim README.md
  - window_name: web
    panes:
      - nvim home/index.md
  - window_name: bash
    layout: even-horizontal
    panes:
      - clear && ls -l
      - nvim Makefile
