session_name: www
start_directory: "~/Documents/topics/personal/static-website"
windows:
  - window_name: readme
    panes:
      - nvim README.md
  - window_name: web
    panes:
      - nvim blog
  - window_name: bash
    layout: even-horizontal
    panes:
      - clear && ls -l
      - nvim Makefile
